function Array_Dipoles(varargin)
%-------------------------------------------------------------------------
% Computation of Bfield generated by an array of permanent magnets (PMs)
%
% Dipole model of PM based on paper by R. Engel-Herbert and T. Hesjedal:
%     R. Engel-Herbert and T. Hesjedal
%     Calculation of the magnetic stray field of a uniaxial magnetic domain
%     J. Appl. Phys., Vol. 97, 2005, 074504
%
% The dipole model also include:
%   - the reaction field due to the other PMs
%   - the nonlinear JH behaviour of PM
%   (B = Mu0*(H+J), with J = f(H))
%
% Two type of simulations are enabled:
% - Deterministic (with all input data defined)
% - Stochastic using MonteCarlo approach (some input data are given in terms
%       of a statistical distribution)
%
% Author: O. Bottauscio (first version: 2025)
%-------------------------------------------------------------------------
Code_Version='1.0';

fprintf('Code: Array_Dipoles, Version: %s\n',Code_Version);
DirRun=pwd;   %Directory di run
fprintf('Running directory: %s\n',DirRun);

% constants
Mu0=4e-7*pi;

% Input from prompt line
n_input=size(varargin,2);
if n_input >= 1
  if strcmp(string(varargin{1}),'[]')
    input_data = 'standard_inputdata.txt';
  else
    input_data = varargin{1};
  end
else
  input_data ='standard_inputdata.txt';
end

% Opening input data file
if isfile(input_data) == 0
  fprintf('File: %s does not exist\n',input_data)
  return
end

% Reading toml file
toml_data = toml.read(input_data);

input_file_description = toml_data.title;
input_file_version = toml_data.version;

% Units
scale = toml_data.unit.scale;

% Read magnets data
MAGNETI_GEO = struct;
[MAGNETI_GEO] = read_labels.readPM(toml_data,MAGNETI_GEO,scale);

% check if magnet geometry modification
[MAGNETI_GEO] = read_labels.readMODGEO(toml_data,scale,MAGNETI_GEO);

% Read material data
MATERIALI = struct;
[MATERIALI] = read_labels.readMATERIAL(toml_data,MATERIALI);

% Read magnet temperature status
TEMPERATURE = struct;
[TEMPERATURE] = read_labels.readTEMPERATURE(toml_data,TEMPERATURE);

% Read computational point (DSV)
POINTS = struct;
[POINTS] = read_labels.readPOINTS(toml_data,POINTS,scale);

% Assign temperature to magnets
MAGNETI_STATO = struct;
if TEMPERATURE.TempVar == 2
% Reading file with magnet temperatures
  T = readtable(TEMPERATURE.file, 'VariableNamingRule', 'preserve');
  TT=table2array(T);
  MAGNETI_STATO.Temperature_magneti=TT(:,4); %Valori T per ciascun magnete
  clear TT
  clear T
else
  MAGNETI_STATO.Temperature_magneti=ones(MAGNETI_GEO.Ndipoli_tot,1)*TEMPERATURE.Tactual;
end

% Input simulations data
SIMUL_DATA = struct;
[SIMUL_DATA] = read_labels.readSIMUL(toml_data,SIMUL_DATA);

if strcmpi(MATERIALI.JHcurve,'NO') && SIMUL_DATA.NL
  fprintf('Nonlinear simulation impossible without JH curves\n')
  return
end
    


%
if strcmp(SIMUL_DATA.Type,'DET')
% ---------------------------------------------------------------------------
% DETERMINISTIC SIMULATION (One Run)
% ---------------------------------------------------------------------------
  TORQUE = struct;
  [TORQUE] = read_labels.readTORQUE(toml_data,TORQUE);
% Initialization
  L=0;
  U=0;
  P=0;
  Tnoto2=0;
  output_JHmag=true;
%
  for n=1:MATERIALI.Nlist
    mat_number=MATERIALI.Lista(n,1);
    Jresidua_relativo(mat_number,1)=1.0;   %For the DET simulations the JH curves are not rescaled
  end
  [MAGNETI_STATO] = dipoles_sub.assegna_valori_dipoles(MAGNETI_GEO,MATERIALI,MAGNETI_STATO,Jresidua_relativo);
  recompute=true;
  first=true;
  [~,~,~,~,BFIELD,MAGNETI_STATO] = dipoles_sub.output_dipoles(first,SIMUL_DATA.reaction,SIMUL_DATA.NL,...
      recompute,MAGNETI_GEO,MAGNETI_STATO,MATERIALI,POINTS,L,U,P,Tnoto2,Mu0,output_JHmag);
  B5 = util.estrai_output(SIMUL_DATA,BFIELD);
  [Bmin,Bmax,Bmean,DEV1_ppm,DEV2_ppm] = util.variability(B5);
  fprintf('Bmin,Bmax,Bmean [mT]: %f %f %f\n',Bmin*1000,Bmax*1000,Bmean*1000);
  fprintf('DEV1 [ppm]: %f\n',DEV1_ppm);
  fprintf('DEV2 [ppm]: %f\n',DEV2_ppm);
  filemat=append(DirRun,'\',SIMUL_DATA.OutputFile);
  save(filemat,'Code_Version','MAGNETI_GEO','MATERIALI','MAGNETI_STATO','TEMPERATURE');
  save(filemat,'SIMUL_DATA','-append');
  save(filemat,'POINTS','BFIELD','-append');
  save(filemat,'Bmin','Bmax','Bmean','DEV1_ppm','DEV2_ppm','-append');
  save(filemat,'input_file_description','input_file_version','-append');
%
  if TORQUE.flag
    flag_all=false;
    [TORQUE] = dipoles_sub.compute_torque(flag_all,TORQUE,MAGNETI_GEO,MAGNETI_STATO,Mu0);
    file_torque=append(DirRun,'\',TORQUE.OutputFile);
    momento_total=TORQUE.momento_total;
    save(file_torque,'momento_total');
    save(filemat,'TORQUE','-append');
  end
  fprintf('Results saved in file: %s\n',filemat);


elseif strcmp(SIMUL_DATA.Type,'MC')
% ---------------------------------------------------------------------------
% MonteCarlo SIMULATION
% ---------------------------------------------------------------------------
  MONTECARLO = struct;
  [MONTECARLO] = read_labels.readMONTECARLO(toml_data,MONTECARLO);
  util.summary_MC(MONTECARLO);
  write_every=50;   %write output every 'write_every' times
%
  [MONTECARLO] = monte_carlo.Run_Monte_Carlo(write_every,MONTECARLO,MAGNETI_GEO,MATERIALI,...
      MAGNETI_STATO,SIMUL_DATA,POINTS,Mu0);
%  
  fprintf('Distribution of Bmean - Mean value [mT]: %f,  StdDev [mT]: %f\n',...
      mean(MONTECARLO.raccolta_bmean),std(MONTECARLO.raccolta_bmean));
  fprintf('Distribution of DEV1 - Mean value [ppm]: %f,  StdDev [ppm]: %f\n',...
      mean(MONTECARLO.raccolta_DEV1),std(MONTECARLO.raccolta_DEV1));
  fprintf('Distribution of DEV2 - Mean value [ppm]: %f,  StdDev [ppm]: %f\n',...
      mean(MONTECARLO.raccolta_DEV2),std(MONTECARLO.raccolta_DEV2));
%
  filemat=append(DirRun,'\',SIMUL_DATA.OutputFile);
  save(filemat,'Code_Version','MAGNETI_GEO','MATERIALI','MAGNETI_STATO','TEMPERATURE');
  save(filemat,'SIMUL_DATA','-append');
  save(filemat,'POINTS','-append');
  save(filemat,'MONTECARLO','-append');
  save(filemat,'input_file_description','input_file_version','-append');
  fprintf('Results saved in file: %s\n',filemat);
end

end