function Check_Array_Dipoles(varargin)
%-------------------------------------------------------------------------
% Comparison between computed and measured Bfield generated by an array
%   of permanent magnets (PMs)
%
% Dipole model of PM based on paper by R. Engel-Herbert and T. Hesjedal:
%     R. Engel-Herbert and T. Hesjedal
%     Calculation of the magnetic stray field of a uniaxial magnetic domain
%     J. Appl. Phys., Vol. 97, 2005, 074504
%
% The dipole model also include:
%   - the reaction field due to the other PMs
%   - the nonlinear JH behaviour of PM
%   (B = Mu0*(H+J), with J = f(H))
%
% Author: O. Bottauscio (first version: 2025)
%-------------------------------------------------------------------------
Code_Version='1.0';

fprintf('Code: Check_Array_Dipoles, Version: %s\n',Code_Version);
DirRun=pwd;   %Directory di run
fprintf('Running directory: %s\n',DirRun);

% constants
Mu0=4e-7*pi;

% Input from prompt line
n_input=size(varargin,2);
if n_input >= 1
  input_data = varargin{1};
else
  fprintf('Input file missing\n')
end
if ~contains(input_data,'.toml')
  input_data=append(input_data,'.toml');
end

% Opening input data file
if isfile(input_data) == 0
  fprintf('File: %s does not exist\n',input_data)
  return
end

% Reading toml file
toml_data = toml.read(input_data);

% Units
[scale] = read_labels.readUnit(toml_data);

% Read magnets data
MAGNETI_GEO = struct;
[ierr,MAGNETI_GEO] = read_labels.readPM(toml_data,MAGNETI_GEO,scale);
if ierr > 0
    return
end

% check if magnet geometry modification
[ierr,MAGNETI_GEO] = read_labels.readMODGEO(toml_data,scale,MAGNETI_GEO);
if ierr > 0
    return
end

% Read material data
MATERIALI = struct;
[ierr,MATERIALI] = read_labels.readMATERIAL(toml_data,MATERIALI);
if ierr > 0
    return
end

% Read magnet temperature status
TEMPERATURE = struct;
[ierr,TEMPERATURE] = read_labels.readTEMPERATURE(toml_data,TEMPERATURE);
if ierr > 0
    return
end

% Assign temperature to magnets
MAGNETI_STATO = struct;
[MAGNETI_STATO] = dipoles_sub.assign_temperature_to_PM(TEMPERATURE,MAGNETI_GEO,MAGNETI_STATO,MATERIALI);

% Input simulations data
SIMUL_DATA = struct;
[ierr,SIMUL_DATA] = read_labels.readSIMUL(toml_data,SIMUL_DATA);
if ierr > 0
    return
end

if strcmpi(MATERIALI.JHcurve,'NO') && SIMUL_DATA.NL
  fprintf('Nonlinear simulation impossible without JH curves\n')
  return
end

for n=1:MATERIALI.Nlist
  mat_number=MATERIALI.Lista(n,1);
  Jresidua_relativo(mat_number,1)=1.0;   %For the DET simulations the JH curves are not rescaled
end
[MAGNETI_STATO] = dipoles_sub.assegna_valori_dipoles(MAGNETI_GEO,MATERIALI,MAGNETI_STATO,Jresidua_relativo);

% ---------------------------------------------------------------------------
% OPTIONS FOR DIFFERENT OUTPUTS
% ---------------------------------------------------------------------------
if strcmpi(SIMUL_DATA.Bcomponent,'x')
 ic=1;
elseif strcmpi(SIMUL_DATA.Bcomponent,'y')
 ic=2;
elseif strcmpi(SIMUL_DATA.Bcomponent,'z')
 ic=3;
end
%
if SIMUL_DATA.reaction
  [L,U,P,Tnoto2] = dipoles_sub.sistema(MAGNETI_GEO.Ndipoli_tot,MAGNETI_GEO.cubo_dimU2,MAGNETI_GEO.cubo_dimV2,MAGNETI_GEO.cubo_dimW2,...
                   Mu0,MAGNETI_STATO.MuR,MAGNETI_GEO.angle,MAGNETI_GEO.xdip,MAGNETI_GEO.ydip,MAGNETI_GEO.zdip);
  [J,~] = dipoles_sub.compute_J_dipoles(SIMUL_DATA.reaction,SIMUL_DATA.NL,MAGNETI_GEO.mat_number,MATERIALI.HJcurve_all,MATERIALI.HJcurve_all_points,MAGNETI_GEO.Ndipoli_tot,...
          MAGNETI_STATO.Jresidua_magneti,MAGNETI_STATO.Hc_magneti,MAGNETI_STATO.JrNL,MAGNETI_STATO.HcNL,Mu0,MAGNETI_STATO.MuR,L,U,P,Tnoto2);
else
  [J,~] = dipoles_sub.compute_J_dipoles(SIMUL_DATA.reaction,SIMUL_DATA.NL,MAGNETI_GEO.mat_number,MATERIALI.HJcurve_all,MATERIALI.HJcurve_all_points,MAGNETI_GEO.Ndipoli_tot,...
          MAGNETI_STATO.Jresidua_magneti,MAGNETI_STATO.Hc_magneti,MAGNETI_STATO.JrNL,MAGNETI_STATO.HcNL,Mu0,MAGNETI_STATO.MuR,[],[],[],[]);
end
%
if toml_data.check_outputs.Z_lines.flag
%------------------Output 1------------------------------------
  Dirpoint1D=toml_data.check_outputs.Z_lines.DirData;
  ListaNomi=toml_data.check_outputs.Z_lines.Files;
  Nlinee=length(ListaNomi);
  figure(1)
  x0=10;
  y0=10;
  width=1000;
  height=1000;
  set(1,'position',[x0,y0,width,height]);
  tcl = tiledlayout(4,2);
  tcl.TileSpacing = 'tight';
  maxB=0;
  minB=100;

  titoli=["\alpha = 0°","\alpha = 45°","\alpha = 90°","\alpha = 135°",...
          "\alpha = 180°","\alpha = 225°","\alpha = 270°","\alpha = 315°"];

  for nl=1:Nlinee
    Nome1D=string(ListaNomi(nl));
%------------------------------------------------------
%  Lettura punti di calcolo (mappatura 1D)
%------------------------------------------------------
    if Dirpoint1D==""
      filepoint=Nome1D;
    else
      filepoint=append(Dirpoint1D,'\',Nome1D);
    end
    aus=load(filepoint);
% computational points
    POINTS = struct;
    POINTS.Npoint=size(aus.acqPos,1);
    raggio=aus.acqPos(:,1)*1e-3;
    angolo=aus.acqPos(:,2)*pi/180.;
    POINTS.xp=raggio.*sin(angolo);
    POINTS.yp=raggio.*cos(angolo);
    POINTS.zp=aus.acqPos(:,3)*1e-3;
%
    Bmis=-aus.realField(:,ic);
    if max(Bmis)>maxB
        maxB=max(Bmis);
    end
    if min(Bmis)<minB
        minB=min(Bmis);
    end
    [BFIELD.Bx5,BFIELD.By5,BFIELD.Bz5] = dipoles_sub.compute_field(POINTS.Npoint,POINTS.xp,POINTS.yp,POINTS.zp,...
        MAGNETI_GEO.Ndipoli_tot,MAGNETI_GEO.xdip,MAGNETI_GEO.ydip,MAGNETI_GEO.zdip,MAGNETI_GEO.angle,...
        MAGNETI_GEO.cubo_dimU2,MAGNETI_GEO.cubo_dimV2,MAGNETI_GEO.cubo_dimW2,J,Mu0);
    B5 = util.estrai_output(SIMUL_DATA,BFIELD);
    B5=B5*1000.;
    if max(B5)>maxB
        maxB=max(B5);
    end
    if min(B5)<minB
        minB=min(B5);
    end
    nexttile(tcl)
    hold on
    plot(POINTS.zp,B5,'--k','LineWidth',2)
    plot(POINTS.zp,Bmis,'k','LineWidth',2)
    xlabel('Position (m)');
    ylabel('B_{x} (mT)');
    grid on
%    title(Nome1D)
    title(titoli(nl));
  end
  for nl=1:Nlinee
    nexttile(nl)
    ylim([minB maxB]);
  end
  leg = legend('Computed','Measured','Orientation', 'Horizontal');
  leg.Layout.Tile = 'north';  

end

if toml_data.check_outputs.XYZ.flag
%------------------Output 2------------------------------------
  figure(2)
  x0=10;
  y0=10;
  width=1000;
  height=1000;
  set(2,'position',[x0,y0,width,height]);
  tcl = tiledlayout(3,1);
  tcl.TileSpacing = 'tight';
% computational points
  POINTS = struct;
  POINTS.Npoint=200;
  maxB=0;
  minB=100;
  for nl=1:3
%------------------------------------------------------
%  Lettura punti di calcolo (mappatura 1D)
%------------------------------------------------------
    raggio=transpose(linspace(-0.12,0.12,POINTS.Npoint));
    dangolo=0.0;
    if nl==1
      angolo=90+dangolo;
      POINTS.xp=raggio*sin(angolo/180*pi);
      POINTS.yp=raggio*cos(angolo/180*pi);
      POINTS.zp=zeros(POINTS.Npoint,1);
      line=POINTS.xp;
      ll='Position x (m)';
      tt='X axis';
    elseif nl==2
      angolo=0+dangolo;
      POINTS.xp=raggio*sin(angolo/180*pi);
      POINTS.yp=raggio*cos(angolo/180*pi);
      POINTS.zp=zeros(POINTS.Npoint,1);
      line=POINTS.yp;
      ll='Position y (m)';
      tt='Y axis';
    elseif nl==3
      POINTS.xp=zeros(POINTS.Npoint,1);
      POINTS.yp=zeros(POINTS.Npoint,1);
      POINTS.zp=raggio;
      line=POINTS.zp;
      ll='Position z (m)';
      tt='Z axis';
    end
    [BFIELD.Bx5,BFIELD.By5,BFIELD.Bz5] = dipoles_sub.compute_field(POINTS.Npoint,POINTS.xp,POINTS.yp,POINTS.zp,...
        MAGNETI_GEO.Ndipoli_tot,MAGNETI_GEO.xdip,MAGNETI_GEO.ydip,MAGNETI_GEO.zdip,MAGNETI_GEO.angle,...
        MAGNETI_GEO.cubo_dimU2,MAGNETI_GEO.cubo_dimV2,MAGNETI_GEO.cubo_dimW2,J,Mu0);
    B5 = util.estrai_output(SIMUL_DATA,BFIELD);
    B5=B5*1000.;
    if max(B5)>maxB
        maxB=max(B5);
    end
    if min(B5)<minB
        minB=min(B5);
    end
    nexttile(tcl)
    hold on
    plot(line,B5,'k','LineWidth',2)
    xlabel(ll);
    ylabel('B (mT)');
    title(tt)
    grid on
  end
  for nl=1:3
    nexttile(nl)
    ylim([minB maxB]);
  end
end

if toml_data.check_outputs.DSV.flag
%------------------Output 3------------------------------------
  Dirpoint3D=toml_data.check_outputs.DSV.DirData;
  Nome3D=string(toml_data.check_outputs.DSV.File);
  figure(3)
  x0=10;
  y0=10;
  width=1000;
  height=1000;
  set(3,'position',[x0,y0,width,height]);
  tcl = tiledlayout(2,1);
  tcl.TileSpacing = 'tight';
%------------------------------------------------------
%  Lettura punti di calcolo (mappatura 3D)
%  (mappatura cartesiana)
%------------------------------------------------------
  if Dirpoint3D==""
      filepoint=Nome3D;
  else
     filepoint=append(Dirpoint3D,'\',Nome3D);
  end
  aus=load(filepoint);

% computational points
  POINTS = struct;
  POINTS.Npoint=size(aus.acqPos,1);
  POINTS.xp=aus.acqPos(:,1)*1e-3;
  POINTS.yp=aus.acqPos(:,2)*1e-3;
  POINTS.zp=aus.acqPos(:,3)*1e-3;
  Bmis=-aus.realField(:,ic);
  [BFIELD.Bx5,BFIELD.By5,BFIELD.Bz5] = dipoles_sub.compute_field(POINTS.Npoint,POINTS.xp,POINTS.yp,POINTS.zp,...
        MAGNETI_GEO.Ndipoli_tot,MAGNETI_GEO.xdip,MAGNETI_GEO.ydip,MAGNETI_GEO.zdip,MAGNETI_GEO.angle,...
        MAGNETI_GEO.cubo_dimU2,MAGNETI_GEO.cubo_dimV2,MAGNETI_GEO.cubo_dimW2,J,Mu0);
  Bcomp = util.estrai_output(SIMUL_DATA,BFIELD);
  Bcomp=Bcomp*1000.;
  maxB=max(Bcomp);
  minB=min(Bcomp);
  if max(Bmis) > maxB
      maxB=max(Bmis);
  end
  if min(Bmis) < minB
      minB=min(Bmis);
  end
  nexttile(tcl)
  plot(Bcomp,'r');
  hold on
  yline(mean(Bcomp),'--r');
  xlabel('ID Point');
  ylabel('Bx (mT)');
  title('Simulated');
  grid on
  nexttile(tcl)
  plot(Bmis,'b');
  hold on
  yline(mean(Bmis),'--b');
  xlabel('ID Point');
  ylabel('Bx (mT)');
  title('Measured');
  grid on
  for nl=1:2
    nexttile(nl)
    ylim([minB maxB]);
  end
  [~,~,Bmean_mis,Dev1_mis,Dev2_mis] = util.variability(Bmis);
  [~,~,Bmean_comp,Dev1_comp,Dev2_comp] = util.variability(Bcomp);
  fprintf('Bmean (mT) - Mis: %f,  Comp: %f\n',Bmean_mis,Bmean_comp);
  fprintf('Dev1 (ppm) - Mis: %f,  Comp: %f\n',Dev1_mis,Dev1_comp);
  fprintf('Dev2 (ppm) - Mis: %f,  Comp: %f\n',Dev2_mis,Dev2_comp);
end

end